name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: "Version Preview URL: ⏳deployment is in progress..."

      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup

      - name: Restore build cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx', '!node_modules/**/*') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-
            ${{ runner.os }}-nextjs-

      - uses: nemolize/set-wrangler-name@v1
      - run: npx opennextjs-cloudflare build

      - id: deploy
        name: Deploy
        run: |
          OUTPUT=$(npx opennextjs-cloudflare ${{ github.event_name == 'pull_request' && 'upload' || 'deploy' }})
          echo "$OUTPUT"
          echo "preview_line=$(echo "$OUTPUT" | grep "Version Preview URL:")" >> $GITHUB_OUTPUT
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Add preview URL comment
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: ${{ steps.deploy.outputs.preview_line }}

      - if: failure()
        name: Show error message in sticky comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: "Version Preview URL: ❌deployment failed."
